version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: devconferences
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql